#cloud-config
write_files:
    - path: /run/nginx-html/stuff.html
      owner: root:root
      permissions: "0644"
      content: "<p>This is just some stuff</p>"

runcmd:
    - |
      echo "Installing pre-req packages..."
    - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - apt-key fingerprint 0EBFCD88
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - apt-get update
    - apt-get install docker-ce -y
    #- sudo usermod -a -G docker $USER
    - |
      echo "Enabling and starting docker container..."
    - systemctl enable docker
    - systemctl restart docker
    - mkdir -p /usr/share/nginx/html
    - sudo mv /run/nginx-html/stuff.html /usr/share/nginx/html
    - sudo docker run --name docker-nginx -p 80:80 --mount type=bind,source="/usr/share/nginx/html",target=/usr/share/nginx/html nginx:latest
    
